# permissions for end users to edit redpandas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redpanda-editor-role
rules:
- apiGroups:
  - redpanda.vectorized.io
  resources:
  - redpandas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redpanda.vectorized.io
  resources:
  - redpandas/status
  verbs:
  - get
