# permissions for end users to view redpandas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redpanda-viewer-role
rules:
- apiGroups:
  - redpanda.vectorized.io
  resources:
  - redpandas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redpanda.vectorized.io
  resources:
  - redpandas/status
  verbs:
  - get
